---
title: "Solow Growth Model"
author: "Augusto Gonzalez-Bonorino"
date: "2024-07-08"
output: html_notebook
---


```{r}
solow_model <- function (s, n, r, a) {
  drdt <- s * r^a - n * r
  return(drdt)
}

s <- 0.3
n <- 0.02
a <- 1/3

r <- seq(0, 100, by = 0.1)

drdt <- solow_model(s, n, r, a)

plot(r, drdt, type = "l", xlab = "r", ylab = "dr/dt")
title("Solow model (a = 1/3)")
abline(h = 0, col = "red")

# add label at r = 0 and r = (s/n)^(3/2)
text(0, 0, "r = 0", pos=3)
text((s/n)^(1/(1-a)), 0, "r = (s/n)^(3/2)", pos=3)
```

```{r}
# simulation of the Solow model possible trajectories for different n
# Parameters
s <- 0.3
a <- 1/3
r <- seq(0, 100, by = 0.1)

# Different values of n to simulate
n_values <- c(0.01, 0.02, 0.03, 0.04)

# Colors for each trajectory
colors <- c("blue", "green", "orange", "purple")

# Plot the initial graph for the first value of n
n <- n_values[1]
drdt <- solow_model(s, n, r, a)
plot(r, drdt, type = "l", col = colors[1], xlab = "r", ylab = "dr/dt", ylim = c(-1, 1))
title("Solow Model (a = 1/3, s = 0.3) with Different n Values")
abline(h = 0, col = "red")

# Plot other trajectories
for (i in 2:length(n_values)) {
  n <- n_values[i]
  drdt <- solow_model(s, n, r, a)
  lines(r, drdt, col = colors[i])
}


# Add legend
legend("topright", legend = sprintf("n = %.2f", n_values), col = colors, lty = 1)

```

```{r}
# simulation of the Solow model possible trajectories for different s
# Parameters
n <- 0.02
a <- 1/3
r <- seq(0, 100, by = 0.1)

s_values <- c(0.1, 0.2, 0.3, 0.4, 0.5)

# Colors for each trajectory
colors <- c("blue", "green", "orange", "purple", "red")

# Plot the initial graph for the first value of n
s <- s_values[1]
drdt <- solow_model(s, n, r, a)
plot(r, drdt, type = "l", col = colors[1], xlab = "r", ylab = "dr/dt", ylim = c(-1, 1))
title("Solow Model (a = 1/3, n = 0.02) with Different s Values")
abline(h = 0, col = "red")

# Plot other trajectories
for (i in 2:length(s_values)) {
  s <- s_values[i]
  drdt <- solow_model(s, n, r, a)
  lines(r, drdt, col = colors[i])
}


# Add legend
legend("topright", legend = sprintf("s = %.2f", s_values), col = colors, lty = 1)
```

```{r}
s <- 0.3
a <- 1/3
n <- 0.02
r <- seq(0, 100, by = 0.1) # capital-labor ratio (x-axis)

y_per_capita <- s * (r)^a # output per worker (y-axis)

plot(r, y_per_capita, type = "l", xlab = "K/L (capital per worker)", ylab = "Y/L (output per worker)")
text(40, 1.1, "s*r^a", pos=3)

title("Solow model (a = 1/3)")

abline(a=c(0,0), b=n, col = "red", lty = 2)
text(20, 0.4, "n*r", pos=3, col="red")

# steady-state
text((s/n)^(1/(1-a)), y_per_capita[400], "steady-state", pos=4, col="red")

# the steady-state with cobb-douglas production function 
# No output unless K and L are positive
# Diminishing marginal productivity of capital
# The steady-state is a stable equilibrium point 
## Whatever the initial value of the capital-labor ratio, the system will develop toward a state of balanced growth at the natural rate.
```

